/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * NotesNet API
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type CreateAccountBody = {
  /**
     * @minLength 4
     * @maxLength 20
     * @pattern ^[a-z0-9]{4,20}$
     */
  username: string;
  /**
     * @minLength 16
     * @maxLength 128
     */
  password: string;
};
