/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * NotesNet API
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type CreateSessionBody = {
  username: string;
  /** @maxLength 128 */
  password: string;
};
