/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * notesnet
 * OpenAPI spec version: 0.1.0
 */

export interface CreateNoteParent {
  /** @nullable */
  order_child?: number | null;
  parent_note_id: string;
  should_listed_as_child?: boolean;
  should_listed_as_parent?: boolean;
}
