/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * notesnet
 * OpenAPI spec version: 0.1.0
 */
import type { CreateNoteParent } from './createNoteParent';

export interface CreateNoteRequest {
  attributes: unknown;
  content: unknown;
  content_type: string;
  parents?: CreateNoteParent[];
  scope_id: string;
  /** @nullable */
  started_at?: string | null;
  /** @nullable */
  summary?: string | null;
  text_for_search: string;
  /** @nullable */
  written_at?: string | null;
}
