/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * notesnet
 * OpenAPI spec version: 0.1.0
 */
import type { GetMeScopePermissions } from './getMeScopePermissions';

export interface GetMeScopesItem {
  created_at: string;
  id: string;
  is_owner: boolean;
  name: string;
  owner_account_id: string;
  permissions: GetMeScopePermissions;
}
