/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * notesnet
 * OpenAPI spec version: 0.1.0
 */
import type { GetMeScopesItem } from './getMeScopesItem';

export interface GetMeScopesResponse {
  items: GetMeScopesItem[];
}
