/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * notesnet
 * OpenAPI spec version: 0.1.0
 */

export interface GetMeScopePermissions {
  can_add_their_notes_to_child: boolean;
  can_modify_notes: boolean;
  can_read_note_revisions: boolean;
}
