/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * notesnet
 * OpenAPI spec version: 0.1.0
 */
import type { ListNotesItem } from './listNotesItem';

export interface ListNotesResponse {
  items: ListNotesItem[];
  /** @nullable */
  next_cursor?: string | null;
  /** @nullable */
  prev_cursor?: string | null;
}
