/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * notesnet
 * OpenAPI spec version: 0.1.0
 */
import type { ListNotesOrderBy } from './listNotesOrderBy';

export type ListNotesParams = {
/**
 * Sort order field (default: written_at)
 */
order_by?: ListNotesOrderBy;
/**
 * Number of items per page (default: 20, max: 100)
 * @nullable
 */
limit?: number | null;
/**
 * Pagination cursor (obtained from next_cursor / prev_cursor in response)
 * @nullable
 */
cursor?: string | null;
};
