/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * notesnet
 * OpenAPI spec version: 0.1.0
 */

export type ListNotesOrderBy = typeof ListNotesOrderBy[keyof typeof ListNotesOrderBy];


export const ListNotesOrderBy = {
  written_at: 'written_at',
  inserted_at: 'inserted_at',
} as const;
