/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * notesnet
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreateSessionRequest,
  CreateSessionResponse,
  CreateUserRequest
} from './schemas';

import { customFetch } from '../client';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type createAccountResponse200 = {
  data: void
  status: 200
}

export type createAccountResponse409 = {
  data: void
  status: 409
}

export type createAccountResponse422 = {
  data: void
  status: 422
}

export type createAccountResponse500 = {
  data: void
  status: 500
}

export type createAccountResponseSuccess = (createAccountResponse200) & {
  headers: Headers;
};
export type createAccountResponseError = (createAccountResponse409 | createAccountResponse422 | createAccountResponse500) & {
  headers: Headers;
};

export type createAccountResponse = (createAccountResponseSuccess | createAccountResponseError)

export const getCreateAccountUrl = () => {




  return `/api/internal/accounts/create`
}

export const createAccount = async (createUserRequest: CreateUserRequest, options?: RequestInit): Promise<createAccountResponse> => {

  return customFetch<createAccountResponse>(getCreateAccountUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUserRequest,)
  }
);}




export const getCreateAccountMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAccount>>, TError,{data: CreateUserRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createAccount>>, TError,{data: CreateUserRequest}, TContext> => {

const mutationKey = ['createAccount'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAccount>>, {data: CreateUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  createAccount(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateAccountMutationResult = NonNullable<Awaited<ReturnType<typeof createAccount>>>
    export type CreateAccountMutationBody = CreateUserRequest
    export type CreateAccountMutationError = void

    export const useCreateAccount = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAccount>>, TError,{data: CreateUserRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAccount>>,
        TError,
        {data: CreateUserRequest},
        TContext
      > => {
      return useMutation(getCreateAccountMutationOptions(options), queryClient);
    }

export type createSessionResponse200 = {
  data: CreateSessionResponse
  status: 200
}

export type createSessionResponse401 = {
  data: void
  status: 401
}

export type createSessionResponse500 = {
  data: void
  status: 500
}

export type createSessionResponseSuccess = (createSessionResponse200) & {
  headers: Headers;
};
export type createSessionResponseError = (createSessionResponse401 | createSessionResponse500) & {
  headers: Headers;
};

export type createSessionResponse = (createSessionResponseSuccess | createSessionResponseError)

export const getCreateSessionUrl = () => {




  return `/api/internal/sessions/create`
}

export const createSession = async (createSessionRequest: CreateSessionRequest, options?: RequestInit): Promise<createSessionResponse> => {

  return customFetch<createSessionResponse>(getCreateSessionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSessionRequest,)
  }
);}




export const getCreateSessionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSession>>, TError,{data: CreateSessionRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createSession>>, TError,{data: CreateSessionRequest}, TContext> => {

const mutationKey = ['createSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSession>>, {data: CreateSessionRequest}> = (props) => {
          const {data} = props ?? {};

          return  createSession(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSessionMutationResult = NonNullable<Awaited<ReturnType<typeof createSession>>>
    export type CreateSessionMutationBody = CreateSessionRequest
    export type CreateSessionMutationError = void

    export const useCreateSession = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSession>>, TError,{data: CreateSessionRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSession>>,
        TError,
        {data: CreateSessionRequest},
        TContext
      > => {
      return useMutation(getCreateSessionMutationOptions(options), queryClient);
    }

